// <auto-generated />
using System;
using Library.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.DAL.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20251206175901_FinalMig")]
    partial class FinalMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library.Models.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nationalite")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nationalite = "Française",
                            Nom = "Hugo",
                            Prenom = "Victor"
                        },
                        new
                        {
                            Id = 2,
                            Nationalite = "Britannique",
                            Nom = "Tolkien",
                            Prenom = "J.R.R."
                        },
                        new
                        {
                            Id = 3,
                            Nationalite = "Britannique",
                            Nom = "Rowling",
                            Prenom = "J.K."
                        },
                        new
                        {
                            Id = 4,
                            Nationalite = "Française",
                            Nom = "Saint-Exupéry",
                            Prenom = "Antoine de"
                        },
                        new
                        {
                            Id = 5,
                            Nationalite = "Britannique",
                            Nom = "Orwell",
                            Prenom = "George"
                        },
                        new
                        {
                            Id = 6,
                            Nationalite = "Française",
                            Nom = "Camus",
                            Prenom = "Albert"
                        },
                        new
                        {
                            Id = 7,
                            Nationalite = "Colombienne",
                            Nom = "García Márquez",
                            Prenom = "Gabriel"
                        },
                        new
                        {
                            Id = 8,
                            Nationalite = "Américaine",
                            Nom = "Hemingway",
                            Prenom = "Ernest"
                        });
                });

            modelBuilder.Entity("Library.Models.Entities.AuthorBook", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("AuthorBooks", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BookId = 1
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 2
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 3
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 4
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 5
                        },
                        new
                        {
                            AuthorId = 6,
                            BookId = 6
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 7
                        },
                        new
                        {
                            AuthorId = 8,
                            BookId = 8
                        });
                });

            modelBuilder.Entity("Library.Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnneePublication")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnneePublication = 1862,
                            Disponible = true,
                            ISBN = "978-2-253-09633-4",
                            Titre = "Les Misérables"
                        },
                        new
                        {
                            Id = 2,
                            AnneePublication = 1954,
                            Disponible = true,
                            ISBN = "978-2-266-15410-9",
                            Titre = "Le Seigneur des Anneaux"
                        },
                        new
                        {
                            Id = 3,
                            AnneePublication = 1997,
                            Disponible = true,
                            ISBN = "978-2-07-054127-3",
                            Titre = "Harry Potter à l'école des sorciers"
                        },
                        new
                        {
                            Id = 4,
                            AnneePublication = 1943,
                            Disponible = false,
                            ISBN = "978-2-07-061275-8",
                            Titre = "Le Petit Prince"
                        },
                        new
                        {
                            Id = 5,
                            AnneePublication = 1949,
                            Disponible = true,
                            ISBN = "978-0-452-28423-4",
                            Titre = "1984"
                        },
                        new
                        {
                            Id = 6,
                            AnneePublication = 1942,
                            Disponible = false,
                            ISBN = "978-2-07-036002-4",
                            Titre = "L'Étranger"
                        },
                        new
                        {
                            Id = 7,
                            AnneePublication = 1967,
                            Disponible = true,
                            ISBN = "978-2-02-037644-2",
                            Titre = "Cent ans de solitude"
                        },
                        new
                        {
                            Id = 8,
                            AnneePublication = 1952,
                            Disponible = true,
                            ISBN = "978-0-684-80122-3",
                            Titre = "Le Vieil Homme et la Mer"
                        });
                });

            modelBuilder.Entity("Library.Models.Entities.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRetourPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetourReelle")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomEmprunteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Penalite")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Borrowings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 4,
                            DateEmprunt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRetourPrevue = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomEmprunteur = "Jean Dupont",
                            Penalite = 0m
                        },
                        new
                        {
                            Id = 2,
                            BookId = 6,
                            DateEmprunt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRetourPrevue = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomEmprunteur = "Marie Laurent",
                            Penalite = 6.00m
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            DateEmprunt = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRetourPrevue = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRetourReelle = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomEmprunteur = "Pierre Martin",
                            Penalite = 0m
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            DateEmprunt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRetourPrevue = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRetourReelle = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomEmprunteur = "Sophie Bernard",
                            Penalite = 5.00m
                        });
                });

            modelBuilder.Entity("Library.Models.Entities.AuthorBook", b =>
                {
                    b.HasOne("Library.Models.Entities.Author", "Author")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Models.Entities.Book", "Book")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Library.Models.Entities.Borrowing", b =>
                {
                    b.HasOne("Library.Models.Entities.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Library.Models.Entities.Author", b =>
                {
                    b.Navigation("AuthorBooks");
                });

            modelBuilder.Entity("Library.Models.Entities.Book", b =>
                {
                    b.Navigation("AuthorBooks");

                    b.Navigation("Borrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
